import idea1 from './images/idea1.jpg';
import pirsagi1 from './images/pirsagi1.jpg';
import sixov1 from './images/sixov1.jpg';
import sixov2 from './images/sixov2.jpg';
import dalga2 from './images/dalga2.jpg';
import dalga3 from './images/dalga3.jpg';
import six1 from './images/six1.jpg';
import naf1 from './images/naftalan1.jpg';

export const beach = [
    {
        id: 1,
        img1: idea1,
        img2: "https://i.pinimg.com/originals/05/1c/09/051c092b257cfc009b3971205def17f6.jpg",
        img3: "https://havingfuninthetexassun.files.wordpress.com/2020/06/img_6708.jpg?w=1024&resize=1140%2C855",
        img4: "https://dmsimgs.visitblackpool.newmindmedia.com/wsimgs/Blackpool-Beach-1_1891865291.jpg",
        img5: "https://static.toiimg.com/thumb/70090588/Bikin.jpg?width=1200&height=900",
        title: "İDEA ictimai çimərlik",
        desc: `"İdea" İctimai Birliyin təşəbbüsü ilə yaradılmış ödənişsiz ictimai çimərlik.`,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 2,
        img1: pirsagi1,
        img2: "https://i.pinimg.com/originals/05/1c/09/051c092b257cfc009b3971205def17f6.jpg",
        img3: "https://havingfuninthetexassun.files.wordpress.com/2020/06/img_6708.jpg?w=1024&resize=1140%2C855",
        img4: "https://dmsimgs.visitblackpool.newmindmedia.com/wsimgs/Blackpool-Beach-1_1891865291.jpg",
        img5: "https://static.toiimg.com/thumb/70090588/Bikin.jpg?width=1200&height=900",
        title: "Pirşağı çimərliyi",
        desc: `Heydər Əliyev Fondunun vitse-prezidenti, IDEA İctimai Birliyinin təsisçisi və rəhbəri Leyla Əliyevanın təşəbbüsü ilə Bakı şəhərində özəl istirahət mərkəzləri və pullu çimərliklərə alternativ olaraq yaradılan pulsuz çimərliklərdən biri də Pirşağı çimərliyidir.Mütəxəsislər bildirir ki, dəniz suyunda COVID-19 ilə yoluxma mümkün deyil, əksinə duz və dəniz suyu viral yükü azaltmağa kömək edir. Duzlu bir mühitdə yaşaya bilməyən bir çox mikroorqanizm var. Dəniz suyunun kimyəvi prosesləri duzların konsentrasiyası ilə əlaqəli yüksək ion gücü, habelə yüksək natrium və xlorid ionları ilə müəyyən edilir. Buna görə də virusların çox ailəsi dənizdə yaşamır. Çimərlikdə koronavirusun yayılmasını çətinləşdirən əsas amil Günəş, dəniz qumunun duzluluğu və səthidir. Ultrabənövşəyi şüalar dəniz duzunun qalıqları səthə düşən virusu məhv edir.`,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 3,
        img1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8H_MttsNnqGZfkpiXs6s25mZW0AdVdKErRQ&usqp=CAU",
        img2: "https://i.pinimg.com/originals/05/1c/09/051c092b257cfc009b3971205def17f6.jpg",
        img3: "https://havingfuninthetexassun.files.wordpress.com/2020/06/img_6708.jpg?w=1024&resize=1140%2C855",
        img4: "https://dmsimgs.visitblackpool.newmindmedia.com/wsimgs/Blackpool-Beach-1_1891865291.jpg",
        img5: "https://static.toiimg.com/thumb/70090588/Bikin.jpg?width=1200&height=900",
        title: "Amburan Beach",
        desc: `Bu kompleksə həftəsonu giriş 25 manat, həftəiçi isə 20 manatdır. Qiymətə çimərlik aksesuarlarından istifadə də daxildir.`,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 4,
        img1: pirsagi1,
        img2: "https://i.pinimg.com/originals/05/1c/09/051c092b257cfc009b3971205def17f6.jpg",
        img3: "https://havingfuninthetexassun.files.wordpress.com/2020/06/img_6708.jpg?w=1024&resize=1140%2C855",
        img4: "https://dmsimgs.visitblackpool.newmindmedia.com/wsimgs/Blackpool-Beach-1_1891865291.jpg",
        img5: "https://static.toiimg.com/thumb/70090588/Bikin.jpg?width=1200&height=900",
        title: "Amburan Beach",
        desc: `Bu kompleksə həftəsonu giriş 25 manat, həftəiçi isə 20 manatdır. Qiymətə çimərlik aksesuarlarından istifadə də daxildir.`,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 5,
        img1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8H_MttsNnqGZfkpiXs6s25mZW0AdVdKErRQ&usqp=CAU",
        img2: "https://i.pinimg.com/originals/05/1c/09/051c092b257cfc009b3971205def17f6.jpg",
        img3: "https://havingfuninthetexassun.files.wordpress.com/2020/06/img_6708.jpg?w=1024&resize=1140%2C855",
        img4: "https://dmsimgs.visitblackpool.newmindmedia.com/wsimgs/Blackpool-Beach-1_1891865291.jpg",
        img5: "https://static.toiimg.com/thumb/70090588/Bikin.jpg?width=1200&height=900",
        title: "Amburan Beach",
        desc: `Bu kompleksə həftəsonu giriş 25 manat, həftəiçi isə 20 manatdır. Qiymətə çimərlik aksesuarlarından istifadə də daxildir.`,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 6,
        img1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8H_MttsNnqGZfkpiXs6s25mZW0AdVdKErRQ&usqp=CAU",
        img2: "https://i.pinimg.com/originals/05/1c/09/051c092b257cfc009b3971205def17f6.jpg",
        img3: "https://havingfuninthetexassun.files.wordpress.com/2020/06/img_6708.jpg?w=1024&resize=1140%2C855",
        img4: "https://dmsimgs.visitblackpool.newmindmedia.com/wsimgs/Blackpool-Beach-1_1891865291.jpg",
        img5: "https://static.toiimg.com/thumb/70090588/Bikin.jpg?width=1200&height=900",
        title: "Amburan Beach",
        desc: `Bu kompleksə həftəsonu giriş 25 manat, həftəiçi isə 20 manatdır. Qiymətə çimərlik aksesuarlarından istifadə də daxildir.`,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 7,
        img1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8H_MttsNnqGZfkpiXs6s25mZW0AdVdKErRQ&usqp=CAU",
        img2: "https://i.pinimg.com/originals/05/1c/09/051c092b257cfc009b3971205def17f6.jpg",
        img3: "https://havingfuninthetexassun.files.wordpress.com/2020/06/img_6708.jpg?w=1024&resize=1140%2C855",
        img4: "https://dmsimgs.visitblackpool.newmindmedia.com/wsimgs/Blackpool-Beach-1_1891865291.jpg",
        img5: "https://static.toiimg.com/thumb/70090588/Bikin.jpg?width=1200&height=900",
        title: "Amburan Beach",
        desc: `Bu kompleksə həftəsonu giriş 25 manat, həftəiçi isə 20 manatdır. Qiymətə çimərlik aksesuarlarından istifadə də daxildir.`,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 8,
        img1: "https://havingfuninthetexassun.files.wordpress.com/2020/06/img_6708.jpg?w=1024&resize=1140%2C855",
        img2: "https://i.pinimg.com/originals/05/1c/09/051c092b257cfc009b3971205def17f6.jpg",
        img3: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8H_MttsNnqGZfkpiXs6s25mZW0AdVdKErRQ&usqp=CAU",
        img4: "https://dmsimgs.visitblackpool.newmindmedia.com/wsimgs/Blackpool-Beach-1_1891865291.jpg",
        img5: "https://static.toiimg.com/thumb/70090588/Bikin.jpg?width=1200&height=900",
        title: "Amburan Beach",
        desc: `Bu kompleksə həftəsonu giriş 25 manat, həftəiçi isə 20 manatdır. Qiymətə çimərlik aksesuarlarından istifadə də daxildir.`,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 9,
        img1: "https://dmsimgs.visitblackpool.newmindmedia.com/wsimgs/Blackpool-Beach-1_1891865291.jpg",
        img2: "https://i.pinimg.com/originals/05/1c/09/051c092b257cfc009b3971205def17f6.jpg",
        img3: "https://havingfuninthetexassun.files.wordpress.com/2020/06/img_6708.jpg?w=1024&resize=1140%2C855",
        img4: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8H_MttsNnqGZfkpiXs6s25mZW0AdVdKErRQ&usqp=CAU",
        img5: "https://static.toiimg.com/thumb/70090588/Bikin.jpg?width=1200&height=900",
        title: "Amburan Beach",
        desc: `Bu kompleksə həftəsonu giriş 25 manat, həftəiçi isə 20 manatdır. Qiymətə çimərlik aksesuarlarından istifadə də daxildir.`,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
]

export const aquaPark = [
    {
        id: 1,
        img1: "http://rubrika.az/uploads/posts/2018-07/1530813503_1530813037_1.jpg",
        img2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvFrj3nSSvbnv1cdJsj2wbt7SAOijMEiEbMA&usqp=CAU",
        img3: sixov1,
        img4: "https://pix10.agoda.net/hotelImages/67789/-1/8a1af6709e5c4cb79f03035987904e33.jpg?s=1024x768",
        img5: "https://4kids.az/uploads/07db5-5.jpg",
        title: 'Dalga Beach Aquapark Resort',
        desc: `Azərbaycanda ən böyük su parkı olan “Dalga Beach Aquapark Resort” Bakının Mərdəkan qəsəbəsində, şəhərin mərkəzindən 37 km, hava limanından isə 17.2 km məsafədə yerləşən, müasir çimərlik istirahəti və əyləncə mərkəzidir. Burada uşaqlı, böyüklü hər kəsin vaxtını səmərəli keçirməsi üçün şərait yaradılıb. "Dalğa Arena"nın yaxınlığında yerləşən kompleksin ümumi ərazisi 5 hektardır. Burada çalışan 310 nəfərlik heyət eyni anda 1200 nəfər qonağa xidmət göstərməyə hazırdır.Qiymət: Həftə içi 0-5 yaş pulsuz, 6-11 yaş 15AZN, 12 yaş üzəri 35AZN (Həftə içi), Həftə sonu: 50AZN `,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 2,
        img1: "http://rubrika.az/uploads/posts/2018-07/1530813503_1530813037_1.jpg",
        img2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvFrj3nSSvbnv1cdJsj2wbt7SAOijMEiEbMA&usqp=CAU",
        img3: sixov1,
        img4: "https://pix10.agoda.net/hotelImages/67789/-1/8a1af6709e5c4cb79f03035987904e33.jpg?s=1024x768",
        img5: "https://4kids.az/uploads/07db5-5.jpg",
        title: 'Nar & Sharab',
        desc: `"Nar & Sharab" restoranının xidmətlərindən istifadə etmək mümkündür. Girişin qiyməti 20 AZN-dir. Bu məbləğə hovuz, duş kabinəsi, "lejanka", dəsmal daxildir. 6 yaşınadək uşaqlara giriş pulsuzdur. `,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 3,
        img1: sixov1,
        img2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvFrj3nSSvbnv1cdJsj2wbt7SAOijMEiEbMA&usqp=CAU",
        img3: sixov2,
        img4: "https://pix10.agoda.net/hotelImages/67789/-1/8a1af6709e5c4cb79f03035987904e33.jpg?s=1024x768",
        img5: "https://4kids.az/uploads/07db5-5.jpg",
        title: 'Aqua Park Şıxov',
        desc: `"Şıx qəsəbəsində yerləşmiş şəhərin ən məşhur çimərik komplekslərindən biridir. Digər çimərliklərdən fərqli olaraq bu yer əla təchiz olunmuşdur. Kompleksin böyük ərazisində həm talvarlar, həm duşlar, çox sayda attraksionlar, barlar, su təpələri, batutlar vardır. Habelə kompleksin tərkibinə böyüklər üçün üç böyük və uşaqlar üçün 1 kiçik hovuz daxildir. Qeyd etmək lazımdır ki, çimərlik bu sahildə ən təmizidir. Düzdür, Şıx çimərliyinin yerləşdiyi şəhər akvatoriyası çox vaxt Abşeron çimərliklərinə nisbətən bir qədər çirk olur, odur ki, çimməyə burada ehtiyatla yanaşmaq lazımdır. Yaxşı olar ki, hovuzlarda çimməyə üstünlük verilsin, onlar da burada kifayət qədərdir. İstirahət edənlərin xidmətinə hovuzun ətrafında rahat yerləşdirilmiş rəngarəng talvarlar altında stollar, uzanmaq üçün taxtlar verilir.  `,
        map: 'Bakı, Şiхov qəsəbəsi, Cənub dəniz sahili AZ1000',
        num: '(+99412) 581-30-30',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 4,
        img1: sixov2,
        img2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvFrj3nSSvbnv1cdJsj2wbt7SAOijMEiEbMA&usqp=CAU",
        img3: sixov1,
        img4: "https://pix10.agoda.net/hotelImages/67789/-1/8a1af6709e5c4cb79f03035987904e33.jpg?s=1024x768",
        img5: "https://4kids.az/uploads/07db5-5.jpg",
        title: 'Nar & Sharab',
        desc: `"Nar & Sharab" restoranının xidmətlərindən istifadə etmək mümkündür. Girişin qiyməti 20 AZN-dir. Bu məbləğə hovuz, duş kabinəsi, "lejanka", dəsmal daxildir. 6 yaşınadək uşaqlara giriş pulsuzdur. `,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 5,
        img1: dalga2,
        img2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvFrj3nSSvbnv1cdJsj2wbt7SAOijMEiEbMA&usqp=CAU",
        img3: sixov1,
        img4: "https://pix10.agoda.net/hotelImages/67789/-1/8a1af6709e5c4cb79f03035987904e33.jpg?s=1024x768",
        img5: "https://4kids.az/uploads/07db5-5.jpg",
        title: 'Nar & Sharab',
        desc: `"Nar & Sharab" restoranının xidmətlərindən istifadə etmək mümkündür. Girişin qiyməti 20 AZN-dir. Bu məbləğə hovuz, duş kabinəsi, "lejanka", dəsmal daxildir. 6 yaşınadək uşaqlara giriş pulsuzdur. `,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 6,
        img1: dalga3,
        img2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvFrj3nSSvbnv1cdJsj2wbt7SAOijMEiEbMA&usqp=CAU",
        img3: sixov1,
        img4: "https://pix10.agoda.net/hotelImages/67789/-1/8a1af6709e5c4cb79f03035987904e33.jpg?s=1024x768",
        img5: "https://4kids.az/uploads/07db5-5.jpg",
        title: 'Nar & Sharab',
        desc: `"Nar & Sharab" restoranının xidmətlərindən istifadə etmək mümkündür. Girişin qiyməti 20 AZN-dir. Bu məbləğə hovuz, duş kabinəsi, "lejanka", dəsmal daxildir. 6 yaşınadək uşaqlara giriş pulsuzdur. `,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 7,
        img1: dalga3,
        img2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvFrj3nSSvbnv1cdJsj2wbt7SAOijMEiEbMA&usqp=CAU",
        img3: sixov1,
        img4: "https://pix10.agoda.net/hotelImages/67789/-1/8a1af6709e5c4cb79f03035987904e33.jpg?s=1024x768",
        img5: "https://4kids.az/uploads/07db5-5.jpg",
        title: 'Nar & Sharab',
        desc: `"Nar & Sharab" restoranının xidmətlərindən istifadə etmək mümkündür. Girişin qiyməti 20 AZN-dir. Bu məbləğə hovuz, duş kabinəsi, "lejanka", dəsmal daxildir. 6 yaşınadək uşaqlara giriş pulsuzdur. `,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 8,
        img1: dalga3,
        img2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvFrj3nSSvbnv1cdJsj2wbt7SAOijMEiEbMA&usqp=CAU",
        img3: sixov1,
        img4: "https://pix10.agoda.net/hotelImages/67789/-1/8a1af6709e5c4cb79f03035987904e33.jpg?s=1024x768",
        img5: "https://4kids.az/uploads/07db5-5.jpg",
        title: 'Nar & Sharab',
        desc: `"Nar & Sharab" restoranının xidmətlərindən istifadə etmək mümkündür. Girişin qiyməti 20 AZN-dir. Bu məbləğə hovuz, duş kabinəsi, "lejanka", dəsmal daxildir. 6 yaşınadək uşaqlara giriş pulsuzdur. `,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 9,
        img1: dalga3,
        img2: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvFrj3nSSvbnv1cdJsj2wbt7SAOijMEiEbMA&usqp=CAU",
        img3: sixov1,
        img4: "https://pix10.agoda.net/hotelImages/67789/-1/8a1af6709e5c4cb79f03035987904e33.jpg?s=1024x768",
        img5: "https://4kids.az/uploads/07db5-5.jpg",
        title: 'Nar & Sharab',
        desc: `"Nar & Sharab" restoranının xidmətlərindən istifadə etmək mümkündür. Girişin qiyməti 20 AZN-dir. Bu məbləğə hovuz, duş kabinəsi, "lejanka", dəsmal daxildir. 6 yaşınadək uşaqlara giriş pulsuzdur. `,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
]

export const sanatorium = [
    {
        id: 1,
        img1: six1,
        img2: "https://nztravelclub.az/img/krugazor1.jpg",
        img3: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM1sdFHaB5i9mmgYwmDUHMLdIsvftG1vtG5p7Sod11Dq4bTyijdP5DYOZFFJjPaQRU7Bo&usqp=CAU",
        img4: "https://e-tibb.az/upload/enterprises/3367677.jpg",
        img5: "https://sanatorium.az/uploads/posts/2016-10/1476966295_2.jpg",
        title: 'Şıx sanatoriyası',
        desc: `"Azərbaycanda həm dövlət, həm də özəl sanatoriyalar fəaliyyət göstərir.    Bu sanatoriyalar müxtəlif xəstəliklərin müalicəsi ilə məşğul olur.    Sanatoriyalarda ürək-damar xəstəlikləri, dayaq-hərəkət sistemi xəstəlikləri (ostexondroz, osteoartroz), uroloji xəstəliklər (xroniki prostatitlər, impotensiya), ginekoloji xəstəliklər (xroniki adneksit, klimakterik sindrom), dəri xəstəlikləri (dermatit, neyrodermit), sinir sistemi xəstəlikləri (depressiya, yuxusuzluq, miqren) və s. müalicə edilir.   Eyni zamanda, sanatoriyalarda təbii palçıq, yod-brom vannaları, naftalan terapiyası və parafin terapiyası də qəbul etmək mümkündür. `,
        map: 'Bakı şəhəri, Səbail rayonu, Namiq Quliyev küç. 45',
        num: '(+99412) 581-22-70',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 2,
        img1: naf1,
        img2: "https://nztravelclub.az/img/krugazor1.jpg",
        img3: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM1sdFHaB5i9mmgYwmDUHMLdIsvftG1vtG5p7Sod11Dq4bTyijdP5DYOZFFJjPaQRU7Bo&usqp=CAU",
        img4: "https://e-tibb.az/upload/enterprises/3367677.jpg",
        img5: "https://sanatorium.az/uploads/posts/2016-10/1476966295_2.jpg",
        title: 'Naftalan sanatoriyası',
        desc: `"Tam pansiyon: səhər, nahar və şam yeməkləri, və həmçinin check up və naftalan nefti ilə müalicələr, Fizioterapiya müayinəsi,massaj,idman müalicəsi(müəllim ilə) qiymətə daxildir.`,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 3,
        img1: six1,
        img2: "https://nztravelclub.az/img/krugazor1.jpg",
        img3: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM1sdFHaB5i9mmgYwmDUHMLdIsvftG1vtG5p7Sod11Dq4bTyijdP5DYOZFFJjPaQRU7Bo&usqp=CAU",
        img4: "https://e-tibb.az/upload/enterprises/3367677.jpg",
        img5: "https://sanatorium.az/uploads/posts/2016-10/1476966295_2.jpg",
        title: `Mərdəkan sanatoriyası`,
        desc: `"Pansionat müalicə işlərində müasir metodika və texnologiyalardan istifadə edir, öz fəaliyyətinin nəticələrinin ümümiləşdirilməsi, qabaqcıl təcrübənin öyrənilməsi əsasında müalicə metodları hazırlayır və təcrübədə tətbiq edir. 100 yerlik olan müəssisədə il ərzində müvafiq yollayış əsasında gəlmiş 1000 nəfərdən artıq vətəndaşa müalicə xidməti göstərilir. Pansionata rəhbərliyi Əmək və Əhalinin Sosial Müdafiəsi Naziri tərəfindən vəzifəyə təyin və azad olunan Baş həkim həyata keçirir.`,
        map: 'Bakı şəhəri, Xəzər rayonu, Mərdəkan qəsəbəsi, Sergey Yesenin küç. 85',
        num: '(+99412) 454-33-78',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 4,
        img1: "https://nztravelclub.az/img/krugazor1.jpg",
        img2: six1,
        img3: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM1sdFHaB5i9mmgYwmDUHMLdIsvftG1vtG5p7Sod11Dq4bTyijdP5DYOZFFJjPaQRU7Bo&usqp=CAU",
        img4: "https://e-tibb.az/upload/enterprises/3367677.jpg",
        img5: "https://sanatorium.az/uploads/posts/2016-10/1476966295_2.jpg",
        title: 'Naftalan sanatoriyası',
        desc: `"Tam pansiyon: səhər, nahar və şam yeməkləri, və həmçinin check up və naftalan nefti ilə müalicələr, Fizioterapiya müayinəsi,massaj,idman müalicəsi(müəllim ilə) qiymətə daxildir.`,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 5,
        img1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM1sdFHaB5i9mmgYwmDUHMLdIsvftG1vtG5p7Sod11Dq4bTyijdP5DYOZFFJjPaQRU7Bo&usqp=CAU",
        img2: six1,
        img3: "https://nztravelclub.az/img/krugazor1.jpg",
        img4: "https://e-tibb.az/upload/enterprises/3367677.jpg",
        img5: "https://sanatorium.az/uploads/posts/2016-10/1476966295_2.jpg",
        title: 'Naftalan sanatoriyası',
        desc: `"Tam pansiyon: səhər, nahar və şam yeməkləri, və həmçinin check up və naftalan nefti ilə müalicələr, Fizioterapiya müayinəsi,massaj,idman müalicəsi(müəllim ilə) qiymətə daxildir.`,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 6,
        img1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM1sdFHaB5i9mmgYwmDUHMLdIsvftG1vtG5p7Sod11Dq4bTyijdP5DYOZFFJjPaQRU7Bo&usqp=CAU",
        img2: six1,
        img3: "https://nztravelclub.az/img/krugazor1.jpg",
        img4: "https://e-tibb.az/upload/enterprises/3367677.jpg",
        img5: "https://sanatorium.az/uploads/posts/2016-10/1476966295_2.jpg",
        title: 'Naftalan sanatoriyası',
        desc: `"Tam pansiyon: səhər, nahar və şam yeməkləri, və həmçinin check up və naftalan nefti ilə müalicələr, Fizioterapiya müayinəsi,massaj,idman müalicəsi(müəllim ilə) qiymətə daxildir.`,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 7,
        img1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM1sdFHaB5i9mmgYwmDUHMLdIsvftG1vtG5p7Sod11Dq4bTyijdP5DYOZFFJjPaQRU7Bo&usqp=CAU",
        img2: six1,
        img3: "https://nztravelclub.az/img/krugazor1.jpg",
        img4: "https://e-tibb.az/upload/enterprises/3367677.jpg",
        img5: "https://sanatorium.az/uploads/posts/2016-10/1476966295_2.jpg",
        title: 'Naftalan sanatoriyası',
        desc: `"Tam pansiyon: səhər, nahar və şam yeməkləri, və həmçinin check up və naftalan nefti ilə müalicələr, Fizioterapiya müayinəsi,massaj,idman müalicəsi(müəllim ilə) qiymətə daxildir.`,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 8,
        img1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM1sdFHaB5i9mmgYwmDUHMLdIsvftG1vtG5p7Sod11Dq4bTyijdP5DYOZFFJjPaQRU7Bo&usqp=CAU",
        img2: six1,
        img3: "https://nztravelclub.az/img/krugazor1.jpg",
        img4: "https://e-tibb.az/upload/enterprises/3367677.jpg",
        img5: "https://sanatorium.az/uploads/posts/2016-10/1476966295_2.jpg",
        title: 'Naftalan sanatoriyası',
        desc: `"Tam pansiyon: səhər, nahar və şam yeməkləri, və həmçinin check up və naftalan nefti ilə müalicələr, Fizioterapiya müayinəsi,massaj,idman müalicəsi(müəllim ilə) qiymətə daxildir.`,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
    {
        id: 9,
        img1: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM1sdFHaB5i9mmgYwmDUHMLdIsvftG1vtG5p7Sod11Dq4bTyijdP5DYOZFFJjPaQRU7Bo&usqp=CAU",
        img2: six1,
        img3: "https://nztravelclub.az/img/krugazor1.jpg",
        img4: "https://e-tibb.az/upload/enterprises/3367677.jpg",
        img5: "https://sanatorium.az/uploads/posts/2016-10/1476966295_2.jpg",
        title: 'Naftalan sanatoriyası',
        desc: `"Tam pansiyon: səhər, nahar və şam yeməkləri, və həmçinin check up və naftalan nefti ilə müalicələr, Fizioterapiya müayinəsi,massaj,idman müalicəsi(müəllim ilə) qiymətə daxildir.`,
        map: 'Naftalan şəhəri, Şirvan prospekti 31',
        num: '050-570-20-00',
        price: "25AZN",
        likeStatus: false,
    },
]

export const comments = [
    {
        id: 1,
        comment: "Burda olmuşam.Əla yerdi!Hərkəsə tövsiyyə edirəm!"
    },
    {
        id: 2,
        comment: "Belədəəə....Xoşlamadım!Yenədə özünüz bilin.."
    },
]


